# __Proyecto - Grupo 3__
## _Aprendizaje automático y minería de datos_
### _Integrantes:_

- Anastasia Minina
- Cristhian Burbano
- Denis Chancay
- Erick Figueroa

## 1. Definición del problema
La esperanza de vida de las personas es un valor que ha ído cambiando a lo largo del tiempo, desde la antiguiedad hasta la actualidad varia acorde a la forma de vida, factores geográficos, políticos, económicos, entre otros; que afectan de distintas formas la esperanza de vida en las personas. Relatos bíblicos dicen que algunas personas sobrepasaban facilmente los 200 años; después, guerras, pandemias y hambrunas reducieron el tiempo de vida en algunas zonas del planeta. Se buscará un dataset que contenga información de como ha ido variando la esperanza de vida de las personas en los últimos años. Con lo cual podremos hacer analisis de esa información basandonos en las siguientes preguntas:

- ¿Realmente afectan los diferentes factores predictivos elegidos inicialmente a la esperanza de vida? 
- ¿Cuáles son las variables predictivas que afectan realmente a la esperanza de vida?
- ¿Debería un país con un valor de esperanza de vida más bajo (<65) aumentar su gasto sanitario para mejorar su esperanza media de vida?
- ¿Cómo afectan las tasas de mortalidad infantil y adulta a la esperanza de vida?
- ¿Tiene la esperanza de vida una correlación positiva o negativa con los hábitos alimenticios, el estilo de vida, el ejercicio, el tabaquismo, el alcohol, etc.?
- ¿Cuál es el impacto de la educación en la esperanza de vida de los humanos?
- ¿Tiene la esperanza de vida una relación positiva o negativa con el consumo de alcohol?
- ¿Tienden los países densamente poblados a tener una esperanza de vida más baja?
- ¿Cuál es el impacto de la cobertura de inmunización en la esperanza de vida?

## 2. Obtención del dataset
Se encontró el dataset de esperanza de vida en la plataforma __Kaggle__ en esta dirección web: https://www.kaggle.com/datasets/kumarajarshi/life-expectancy-who/data. El datset contiene datos recopilados de 15 años, entre los años 2000 al 2015 de la esperanza de vida de las personas en 193 países, mismos que fueron tomados del repositorio de datos del Observatorio Mundial de la Salud (GHO) de la Organización Mundial de la Salud (OMS).

In [ ]:
%pip install pandas
%pip install matplotlib seaborn numpy

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('C:/Cristhian Burbano/Mestría Gestion y Analitica de Datos/5 Aprendizaje automatica y mineria de datos/Proyecto/Life Expectancy Data.csv')

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

## 3. Exploración de datos.
Realizaremos una explorción inicial del dataset, sus dimenciones, ver sus estadísticas descriptivas, tipos de datos, correlaciones y visualizaciones.

In [ ]:
print("Dimensiones: ", df.shape)

Dimensiones:  (2938, 22)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   str
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   str
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), str(2)
memory usage: 505.1 KB

In [16]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [14]:
df.describe().T.round(2)

,count,mean,std,min,25%,50%,75%,max
Year,2938.0,2007.52,4.61,2000.00,2004.00,2008.00,2012.00,2.015000e+03
Life expectancy,2928.0,69.22,9.52,36.30,63.10,72.10,75.70,8.900000e+01
Adult Mortality,2928.0,164.80,124.29,1.00,74.00,144.00,228.00,7.230000e+02
infant deaths,2938.0,30.30,117.93,0.00,0.00,3.00,22.00,1.800000e+03
Alcohol,2744.0,4.60,4.05,0.01,0.88,3.76,7.70,1.787000e+01
percentage expenditure,2938.0,738.25,1987.91,0.00,4.69,64.91,441.53,1.947991e+04
Hepatitis B,2385.0,80.94,25.07,1.00,77.00,92.00,97.00,9.900000e+01
Measles,2938.0,2419.59,11467.27,0.00,0.00,17.00,360.25,2.121830e+05
BMI,2904.0,38.32,20.04,1.00,19.30,43.50,56.20,8.730000e+01
under-five deaths,2938.0,42.04,160.45,0.00,0.00,4.00,28.00,2.500000e+03
Polio,2919.0,82.55,23.43,3.00,78.00,93.00,97.00,9.900000e+01
Total expenditure,2712.0,5.94,2.50,0.37,4.26,5.76,7.49,1.760000e+01
Diphtheria,2919.0,82.32,23.72,2.00,78.00,93.00,97.00,9.900000e+01
HIV/AIDS,2938.0,1.74,5.08,0.10,0.10,0.10,0.80,5.060000e+01
GDP,2490.0,7483.16,14270.17,1.68,463.94,1766.95,5910.81,1.191727e+05
Population,2286.0,12753375.12,61012096.51,34.00,195793.25,1386542.00,7420359.00,1.293859e+09
thinness 1-19 years,2904.0,4.84,4.42,0.10,1.60,3.30,7.20,2.770000e+01
thinness 5-9 years,2904.0,4.87,4.51,0.10,1.50,3.30,7.20,2.860000e+01
Income composition of resources,2771.0,0.63,0.21,0.00,0.49,0.68,0.78,9.500000e-01
Schooling,2775.0,11.99,3.36,0.00,10.10,12.30,14.30,2.070000e+01

In [21]:
df.describe(include=['object', 'category', 'str'])

            Country      Status
count          2938        2938
unique          193           2
top     Afghanistan  Developing
freq             16        2426

In [25]:
#%pip install dtale
import dtale
dtale.show(df)

In [27]:
#%pip install sweetviz
import sweetviz as sv
report = sv.analyze(df)
report.show_html('reporte_eda.html')

c:\Users\cburbanop\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Feature: Year                                |▊         | [  9%]   00:00 -> (00:00 left)2026-09-11 18:34:26,640 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:26,667 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:26,736 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:26,760 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:26,850 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:26,869 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:26,955 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:26,982 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,071 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,100 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: Status                              |█▎        | [ 13%]   00:00 -> (00:04 left)2026-09-11 18:34:27,204 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,218 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,266 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,280 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: Life expectancy                     |█▋        | [ 17%]   00:00 -> (00:03 left)2026-09-11 18:34:27,360 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,382 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,443 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,462 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,538 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,557 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,636 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,662 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,740 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,771 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: Adult Mortality                     |██▏       | [ 22%]   00:01 -> (00:05 left)2026-09-11 18:34:27,864 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,884 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,938 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:27,959 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,042 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,062 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,143 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,171 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,299 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,331 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: infant deaths                       |██▌       | [ 26%]   00:01 -> (00:06 left)2026-09-11 18:34:28,429 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,450 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,506 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,528 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,614 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,633 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,720 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,745 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,830 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,864 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: Alcohol                             |███       | [ 30%]   00:02 -> (00:06 left)2026-09-11 18:34:28,956 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:28,975 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,032 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,054 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,146 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,165 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,248 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,273 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,358 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,395 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: percentage expenditure              |███▍      | [ 35%]   00:02 -> (00:06 left)2026-09-11 18:34:29,492 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,517 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,582 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,604 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,702 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,725 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,809 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,834 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,920 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:29,952 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: Hepatitis B                         |███▉      | [ 39%]   00:03 -> (00:06 left)2026-09-11 18:34:30,072 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,093 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,155 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,177 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,256 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,275 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,360 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,382 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,461 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,494 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: Measles                             |████▎     | [ 43%]   00:03 -> (00:06 left)2026-09-11 18:34:30,588 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,612 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,674 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,695 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,772 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,794 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,882 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,905 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:30,984 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,016 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature:  BMI                                |████▊     | [ 48%]   00:04 -> (00:06 left)2026-09-11 18:34:31,106 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,140 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,226 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,252 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,528 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,549 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,628 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,651 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,734 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,763 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: under-five deaths                   |█████▏    | [ 52%]   00:05 -> (00:06 left)2026-09-11 18:34:31,846 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,868 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,932 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:31,955 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,032 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,051 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,135 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,159 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,243 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,275 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: Polio                               |█████▋    | [ 57%]   00:05 -> (00:05 left)2026-09-11 18:34:32,366 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,389 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,451 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,472 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,582 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,602 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,689 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,720 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,797 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,828 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: Total expenditure                   |██████    | [ 61%]   00:06 -> (00:05 left)2026-09-11 18:34:32,929 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:32,955 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,015 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,038 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,124 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,144 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,231 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,256 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,353 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,387 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: Diphtheria                          |██████▌   | [ 65%]   00:06 -> (00:04 left)2026-09-11 18:34:33,487 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,511 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,576 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,599 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,684 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,703 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,786 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,813 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,891 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:33,928 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature:  HIV/AIDS                           |██████▉   | [ 70%]   00:07 -> (00:03 left)2026-09-11 18:34:34,070 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,094 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,161 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,183 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,263 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,283 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,366 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,390 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,472 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,509 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: GDP                                 |███████▍  | [ 74%]   00:08 -> (00:03 left)2026-09-11 18:34:34,619 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,643 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,710 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,733 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,834 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,857 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,939 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:34,966 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,060 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,096 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature: Population                          |███████▊  | [ 78%]   00:08 -> (00:02 left)2026-09-11 18:34:35,200 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,226 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,290 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,314 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,398 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,419 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,505 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,532 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,628 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,663 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
Feature:  thinness  1-19 years               |████████▎ | [ 83%]   00:09 -> (00:02 left)2026-09-11 18:34:35,753 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,777 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.
2026-09-11 18:34:35,840 - WARNING  - findfont: Failed to find font weight normal for Roboto, now using 500.

Report reporte_eda.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.